/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.Customer.CustomerDirectory;
import Business.DB4OUtil.DB4OUtil;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ui.RestaurantAdmin.AdminWorkArea;
import ui.SystemAdminWorkArea.SystemAdminWorkAreaPanel;
import userinterface.CustomerRole.CustomerOrder;
import userinterface.DeliveryMan.OrdersDelivery;
import userinterface.RestaurantAdmin.AdminArea;
import userinterface.SystemAdminWorkArea.SystemAdminWorkArea;

/**
 *
 * @author sarveshzeke
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    EcoSystem ecosystem;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    UserAccount ua;
    RestaurantDirectory rd;
    
    public MainJFrame() {
        ecosystem = dB4OUtil.retrieveSystem();
        if(ecosystem == null)
        {
            ecosystem = new EcoSystem(new RestaurantDirectory(),new CustomerDirectory(),new DeliveryManDirectory());
        }
        
        this.setSize(1680, 1050);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        usernametf = new javax.swing.JTextField();
        passtf = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usernametf, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(passtf)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(usernametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(passtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(loginbtn)
                .addGap(34, 34, 34)
                .addComponent(logoutbtn)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        container.setBackground(new java.awt.Color(255, 204, 153));
        container.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/sarveshzeke/Downloads/Restaurant-Management-System-2-1024x409.png")); // NOI18N
        container.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        String username = usernametf.getText();
        String password = passtf.getText();
        UserAccountDirectory userDirectory = ecosystem.getUserAccountDirectory();
        if(userDirectory.authenticateUserLogin(username, password))
        {
        ArrayList<UserAccount> usersList = userDirectory.getUserAccountList();
        
        this.ua = userDirectory.authenticateUser(username, password);
        if(ua.getRole().toString().equals("Business.Role.SystemAdminRole"))
        {
            logoutbtn.setEnabled(true); 
            usernametf.setEnabled(false);
            
            passtf.setEnabled(false);
            loginbtn.setEnabled(false);
            //EcoSystem ecosystem;
            
            SystemAdminWorkArea sa = new SystemAdminWorkArea(container ,ecosystem);
            container.add("Sysadmin",sa);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.next(container);
        }
        
        else if(ua.getRole().toString().equals("Business.Role.AdminRole"))
        {
            logoutbtn.setEnabled(true); 
            usernametf.setEnabled(false);
            passtf.setEnabled(false);
            loginbtn.setEnabled(false);
            
            AdminArea aw = new AdminArea(container, ua, ecosystem);
            container.add("RestaurantAdmin",aw);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.next(container);
        }
        
        else if(ua.getRole().toString().equals("Business.Role.DeliverManRole"))
        {
            logoutbtn.setEnabled(true); 
            usernametf.setEnabled(false);
            passtf.setEnabled(false);
            loginbtn.setEnabled(false);
            
            OrdersDelivery dw = new OrdersDelivery(container, ua, ecosystem);
            container.add("DeliveryMan",dw);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.next(container);
        }
        
        else if(ua.getRole().toString().equals("Business.Role.CustomerRole"))
        {
            logoutbtn.setEnabled(true); 
            usernametf.setEnabled(false);
            passtf.setEnabled(false);
            loginbtn.setEnabled(false);
            
            CustomerOrder ca = new CustomerOrder(container, ua,ecosystem);
            container.add("Customer",ca);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.next(container);
        }
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid credentials");
        }
      
    }//GEN-LAST:event_loginbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        logoutbtn.setEnabled(false);
        usernametf.setEnabled(true);
        passtf.setEnabled(true);
        loginbtn.setEnabled(true);

        usernametf.setText("");
        passtf.setText("");

        container.removeAll();
        JPanel blankJP = new JPanel();
        container.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
         dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_logoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JTextField passtf;
    private javax.swing.JTextField usernametf;
    // End of variables declaration//GEN-END:variables
}
