/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import business.Ecosystem;
import business.useraccount.UserAccount;
import business.useraccount.UserAccountDirectory;
import java.awt.CardLayout;
import static java.time.Clock.system;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import ui.CustomerPanel.CustomerWorkArea;
import ui.DeliveryMan.DeliveryManWorkArea;
import ui.RestaurantAdmin.RestaurantAdminWorkAreaPanel;
import ui.SystemAdminWorkArea.SystemAdminWorkAreaPanel;

/**
 *
 * @author sarveshzeke
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Ecosystem system;
    UserAccount ua;
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        container = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        usernametf = new javax.swing.JTextField();
        passtf = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(container);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        usernametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametfActionPerformed(evt);
            }
        });

        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(usernametf, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passtf)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(loginbtn)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(usernametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(passtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(loginbtn)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametfActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        String username = usernametf.getText();
        String password = passtf.getText();
        UserAccountDirectory userDirectory = system.getUserAccountDirectory();
        if(userDirectory.verifyUserLogin(username, password))
        {
        ArrayList<UserAccount> usersList = userDirectory.getUserAccountList();
        
        this.ua = userDirectory.authenticateUser(username, password);
        if(ua.getRole().toString().equals("Business.Role.SystemAdminRole"))
        {
           // logoutJButton.setEnabled(true); 
            usernametf.setEnabled(false);
            passtf.setEnabled(false);
            loginbtn.setEnabled(false);
            
            SystemAdminWorkAreaPanel sa = new SystemAdminWorkAreaPanel(container, system);
            container.add("Sysadmin",sa);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.next(container);
        }
        
        else if(ua.getRole().toString().equals("Business.Role.AdminRole"))
        {
            //logoutJButton.setEnabled(true); 
            usernametf.setEnabled(false);
            passtf.setEnabled(false);
            loginbtn.setEnabled(false);
            
            RestaurantAdminWorkAreaPanel aw = new RestaurantAdminWorkAreaPanel(container,ua,system);
            container.add("RestaurantAdmin",aw);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.next(container);
        }
        
        else if(ua.getRole().toString().equals("Business.Role.DeliverManRole"))
        {
            //logoutJButton.setEnabled(true); 
            usernametf.setEnabled(false);
            passtf.setEnabled(false);
            loginbtn.setEnabled(false);
            
            DeliveryManWorkArea dmw = new DeliveryManWorkArea(container, ua, system);
            container.add("DeliveryMan",dmw);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.next(container);
        }
        
        else if(ua.getRole().toString().equals("Business.Role.CustomerRole"))
        {
            //logoutJButton.setEnabled(true); 
            usernametf.setEnabled(false);
            passtf.setEnabled(false);
            loginbtn.setEnabled(false);
            
            CustomerWorkArea ca = new CustomerWorkArea(container, ua,system);
            container.add("Customer",ca);
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.next(container);
        }
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid credentials");
        }
    }//GEN-LAST:event_loginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JTextField passtf;
    private javax.swing.JTextField usernametf;
    // End of variables declaration//GEN-END:variables
}
