/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DeliveryMan;

import business.Customer.CustomerDirectory;
import business.DeliveryMan.DeliveryMan;
import business.DeliveryMan.DeliveryManDirectory;
import business.Ecosystem;
import business.Restaurant.FinalOrder;
import business.Restaurant.Restaurant;
import business.Restaurant.RestaurantDirectory;
import business.useraccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarveshzeke
 */
public class DeliveryManWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryManWorkArea
     */
    JPanel userProcessContainer;
    UserAccount userAcc;
    Ecosystem ecosystem;
    RestaurantDirectory resdir;
    CustomerDirectory cstdir;
    DeliveryMan delmn;
    DeliveryManDirectory deldir;
    Restaurant rst;
    
    public DeliveryManWorkArea(JPanel UserProcessContainer,UserAccount ua, Ecosystem system) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        delmantable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        delmanworkarearefreshbtn = new javax.swing.JButton();

        delmantable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Restaurant", "Item", "Customer", "Order Time", "Status"
            }
        ));
        jScrollPane1.setViewportView(delmantable);

        jButton1.setText("Assign");

        jButton2.setText("Order Delivered");

        delmanworkarearefreshbtn.setText("Refresh");
        delmanworkarearefreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delmanworkarearefreshbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(delmanworkarearefreshbtn)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(99, 99, 99)
                        .addComponent(jButton2)
                        .addGap(62, 62, 62))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(delmanworkarearefreshbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void delmanworkarearefreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delmanworkarearefreshbtnActionPerformed
        // TODO add your handling code here:
        refreshtable();
    }//GEN-LAST:event_delmanworkarearefreshbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable delmantable;
    private javax.swing.JButton delmanworkarearefreshbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void refreshtable() {
         DefaultTableModel dm = (DefaultTableModel) delmantable.getModel();
        dm.setRowCount(0);
        resdir = ecosystem.getRestaurantDirectory();
        ArrayList<FinalOrder> orders;
        ArrayList<Restaurant> restos = resdir.getRstrntList();
        for(Restaurant r: restos)
        {
            if(r.getOrdrAcptd() == null)
                r.setOrdrAcptd(new ArrayList<FinalOrder>());
            orders = r.getOrdrAcptd();
            for(FinalOrder f: orders)
            {
                String[] row = {f.getOrderId(),r.getName(),f.getItm(),f.getCustomer(),f.getDate(),f.getStatus()};
                dm.addRow(row);
            }
        }
        delmantable.setModel(dm);
        
        
    
    }
}
