/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdmin;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Order.FinalOrder;
import Business.Order.Order;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarveshzeke
 */
public class ManageOrders extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrders
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount ua;
    Restaurant resto;
    RestaurantDirectory rd;
    CustomerDirectory cd;
    ArrayList<FinalOrder> ordersList;
    DeliveryManDirectory dd;
    
    public ManageOrders(JPanel userProcessContainer,Restaurant resto,EcoSystem ecosystem) {
        this.userProcessContainer = userProcessContainer;
        this.resto = resto;
        this.ecosystem = ecosystem;
        initComponents();
        populatetree(); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OrdersAvailable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        OrderStatustbl = new javax.swing.JTable();
        orderidcmbbx = new javax.swing.JComboBox<>();
        custtf = new javax.swing.JTextField();
        delcmbbx = new javax.swing.JComboBox<>();
        itemtf = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        OrdersAvailable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Customer", "Item", "Date"
            }
        ));
        jScrollPane1.setViewportView(OrdersAvailable);

        jButton1.setText("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        OrderStatustbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer", "Item", "Status", "Delivery", "Review", "OrderID", "Date"
            }
        ));
        jScrollPane2.setViewportView(OrderStatustbl);

        jButton2.setText("Assign");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("OrderID");

        jLabel2.setText("Customer");

        jLabel3.setText("DeliveryMan");

        jLabel4.setText("Item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(itemtf)
                            .addComponent(orderidcmbbx, javax.swing.GroupLayout.Alignment.TRAILING, 0, 115, Short.MAX_VALUE)
                            .addComponent(custtf)
                            .addComponent(delcmbbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderidcmbbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delcmbbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(resto.getAcceptedOrders() == null)
            resto.setAcceptedOrders(new ArrayList<FinalOrder>());
        ArrayList<FinalOrder> orders = resto.getAcceptedOrders();
        rd = ecosystem.getRestaurantDirectory();
        int orderId = rd.generateOrderId();
        FinalOrder fo = new FinalOrder();
        DefaultTableModel df = (DefaultTableModel) OrdersAvailable.getModel();
        
          int selectedRow = OrdersAvailable.getSelectedRow();
          String customer = df.getValueAt(selectedRow,0).toString();
          String item = df.getValueAt(selectedRow, 1).toString();
          String date = df.getValueAt(selectedRow,2).toString();
          fo.setOrderId(String.valueOf(orderId));
          fo.setCustomer(customer);
          fo.setItem(item);
          fo.setDate(date);
          fo.setRestaurant(resto.getName());
          fo.setStatus("Order Accepted");
          orders.add(fo);
          df.removeRow(selectedRow);
          populatetree();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String orderId =(String) orderidcmbbx.getSelectedItem();
        rd = ecosystem.getRestaurantDirectory();
        FinalOrder f = rd.getOrder(orderId);
        f.setDeliveryMan((String) delcmbbx.getSelectedItem());
        f.setStatus("DeliveryMan Assigned");
        populatetree();
        custtf.setText("");
        itemtf.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void populatetree() {
        
        String resoName = resto.getName();
        cd = ecosystem.getCustomerDirectory();
        DefaultTableModel dt = (DefaultTableModel) OrdersAvailable.getModel();
        dt.setRowCount(0);
        ArrayList<Customer> customers = cd.getCustomerList();
        for(Customer c: customers)
        {
            ArrayList<Order> orders = c.getPreviousOrders();
            for(Order o: orders)
            {
                if(o.getRestaurant().equals(resoName))
                {
                    String[] row = {c.getCustomerName(),o.getItem(),o.getEntryDateTime().toString()};
                    dt.addRow(row);
                }
            }
        }
        
        OrdersAvailable.setModel(dt);
        
        ArrayList<FinalOrder> orders = resto.getAcceptedOrders();
        DefaultTableModel df = (DefaultTableModel) OrderStatustbl.getModel();
        DefaultComboBoxModel dc = new DefaultComboBoxModel();
        df.setRowCount(0);
        for(FinalOrder f: orders)
        {
            String[] row = {f.getCustomer(),f.getItem(),f.getStatus(),f.getDeliveryMan(),f.getReview(),f.getOrderId(),f.getDate()};
            df.addRow(row);
            if(f.getDeliveryMan() == null)
            dc.addElement(f.getOrderId());
        }
        
        OrderStatustbl.setModel(df);
        orderidcmbbx.setModel(dc);
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrderStatustbl;
    private javax.swing.JTable OrdersAvailable;
    private javax.swing.JTextField custtf;
    private javax.swing.JComboBox<String> delcmbbx;
    private javax.swing.JTextField itemtf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> orderidcmbbx;
    // End of variables declaration//GEN-END:variables
}
