/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiframes;

import java.awt.Color;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import person.Person;


/**
 *
 * @author sarveshzeke
 */

public class CreateJFrame extends javax.swing.JPanel {

    /**
     * Creates new form CreateJFrame
     */
    Person p;
    
    public CreateJFrame(Person p) {
        initComponents();
        
        this.p = p;
        gdatapanel.setVisible(false);
        personaldatapanel.setVisible(false);
        nextchkbx.setVisible(false);
        
        jPanel1.setVisible(false);
        btnupload.setVisible(false);
        addnotf.setBackground(Color.LIGHT_GRAY);
        addemailtf.setBackground(Color.LIGHT_GRAY);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gdatapanel = new javax.swing.JPanel();
        namelbl = new javax.swing.JLabel();
        doblbl = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        citylbl = new javax.swing.JLabel();
        citytf = new javax.swing.JTextField();
        countrylbl = new javax.swing.JLabel();
        countrytf = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        namewrong = new javax.swing.JLabel();
        citywrong = new javax.swing.JLabel();
        countrywrong = new javax.swing.JLabel();
        btncleargdatapanel = new javax.swing.JButton();
        datechsr = new com.toedter.calendar.JDateChooser();
        personaldatapanel = new javax.swing.JPanel();
        telnolbl = new javax.swing.JLabel();
        telnotf = new javax.swing.JTextField();
        ssnlbl = new javax.swing.JLabel();
        ssntf = new javax.swing.JTextField();
        btnsavepd = new javax.swing.JButton();
        faxnolbl = new javax.swing.JLabel();
        faxnotf = new javax.swing.JTextField();
        emaillbl = new javax.swing.JLabel();
        emailtf = new javax.swing.JTextField();
        medrecnolbl = new javax.swing.JLabel();
        medrecnotf = new javax.swing.JTextField();
        banknolbl = new javax.swing.JLabel();
        banknotf = new javax.swing.JTextField();
        emailwrong = new javax.swing.JLabel();
        ssnwrong = new javax.swing.JLabel();
        telnowrong = new javax.swing.JLabel();
        btnclearpdatapanel = new javax.swing.JButton();
        faxnowrong = new javax.swing.JLabel();
        medrecnowrong = new javax.swing.JLabel();
        banknowrong = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bennotf = new javax.swing.JTextField();
        bennowrong = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addemailchkbx = new javax.swing.JCheckBox();
        chkbxaddno = new javax.swing.JCheckBox();
        addnotf = new javax.swing.JTextField();
        addemailtf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        uniquenotf = new javax.swing.JTextField();
        uniquenowrong = new javax.swing.JLabel();
        nextchkbx = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        licensenolbl = new javax.swing.JLabel();
        licensenotf = new javax.swing.JTextField();
        vehiclenolbl = new javax.swing.JLabel();
        vehiclenotf = new javax.swing.JTextField();
        devicenolbl = new javax.swing.JLabel();
        devicenotf = new javax.swing.JTextField();
        ipalbl = new javax.swing.JLabel();
        ipatf = new javax.swing.JTextField();
        linkedinlbl = new javax.swing.JLabel();
        linkedintf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        licensenowrong = new javax.swing.JLabel();
        linkedinwrong = new javax.swing.JLabel();
        vehiclenowrong = new javax.swing.JLabel();
        btnclearprodatapanel = new javax.swing.JButton();
        ipawrong = new javax.swing.JLabel();
        devicenowrong = new javax.swing.JLabel();
        serialnolbl = new javax.swing.JLabel();
        serialnotf = new javax.swing.JTextField();
        serialnowrong = new javax.swing.JLabel();
        btnupload = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(51, 0, 51));

        gdatapanel.setBackground(new java.awt.Color(102, 102, 102));

        namelbl.setText("Name:");

        doblbl.setText("DOB:");

        nametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametfActionPerformed(evt);
            }
        });
        nametf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nametfKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nametfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nametfKeyTyped(evt);
            }
        });

        citylbl.setText("City:");

        citytf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                citytfKeyReleased(evt);
            }
        });

        countrylbl.setText("Country:");

        countrytf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                countrytfKeyReleased(evt);
            }
        });

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        namewrong.setForeground(new java.awt.Color(255, 0, 0));

        citywrong.setForeground(new java.awt.Color(255, 0, 51));

        countrywrong.setForeground(new java.awt.Color(255, 0, 0));

        btncleargdatapanel.setText("Clear");
        btncleargdatapanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncleargdatapanelActionPerformed(evt);
            }
        });

        datechsr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datechsrMouseClicked(evt);
            }
        });
        datechsr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                datechsrKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout gdatapanelLayout = new javax.swing.GroupLayout(gdatapanel);
        gdatapanel.setLayout(gdatapanelLayout);
        gdatapanelLayout.setHorizontalGroup(
            gdatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gdatapanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(gdatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namelbl)
                    .addComponent(doblbl)
                    .addComponent(citylbl)
                    .addComponent(countrylbl))
                .addGap(135, 135, 135)
                .addGroup(gdatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gdatapanelLayout.createSequentialGroup()
                        .addGroup(gdatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gdatapanelLayout.createSequentialGroup()
                                .addComponent(countrytf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(countrywrong, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gdatapanelLayout.createSequentialGroup()
                                .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(namewrong, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gdatapanelLayout.createSequentialGroup()
                                .addComponent(citytf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(citywrong, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(213, 213, 213))
                    .addGroup(gdatapanelLayout.createSequentialGroup()
                        .addComponent(datechsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(342, 342, 342))))
            .addGroup(gdatapanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnsave)
                .addGap(37, 37, 37)
                .addComponent(btncleargdatapanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gdatapanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {citywrong, countrywrong, namewrong});

        gdatapanelLayout.setVerticalGroup(
            gdatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gdatapanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(gdatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namewrong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namelbl))
                .addGap(18, 18, 18)
                .addGroup(gdatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gdatapanelLayout.createSequentialGroup()
                        .addComponent(doblbl)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gdatapanelLayout.createSequentialGroup()
                        .addComponent(datechsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(gdatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(citywrong, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(citylbl)
                    .addComponent(citytf))
                .addGap(18, 18, 18)
                .addGroup(gdatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(countrywrong, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(countrylbl)
                    .addComponent(countrytf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(gdatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btncleargdatapanel))
                .addGap(26, 26, 26))
        );

        gdatapanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {citywrong, countrywrong, namewrong});

        personaldatapanel.setBackground(new java.awt.Color(204, 255, 204));

        telnolbl.setText("Tel No:");

        telnotf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telnotfActionPerformed(evt);
            }
        });
        telnotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telnotfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telnotfKeyTyped(evt);
            }
        });

        ssnlbl.setText("SSN:");

        ssntf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssntfActionPerformed(evt);
            }
        });
        ssntf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ssntfKeyReleased(evt);
            }
        });

        btnsavepd.setText("Save");
        btnsavepd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavepdActionPerformed(evt);
            }
        });

        faxnolbl.setText("Fax No:");

        faxnotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                faxnotfKeyReleased(evt);
            }
        });

        emaillbl.setText("Email:");

        emailtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailtfKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailtfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailtfKeyTyped(evt);
            }
        });

        medrecnolbl.setText("Medical Rec No:");

        medrecnotf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medrecnotfActionPerformed(evt);
            }
        });
        medrecnotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                medrecnotfKeyReleased(evt);
            }
        });

        banknolbl.setText("Bank_Acc_No:");

        banknotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                banknotfKeyReleased(evt);
            }
        });

        emailwrong.setForeground(new java.awt.Color(204, 204, 204));
        emailwrong.setText("java100@gmail.com");
        emailwrong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailwrongKeyReleased(evt);
            }
        });

        ssnwrong.setForeground(new java.awt.Color(204, 204, 204));
        ssnwrong.setText("eg;887-88-7867");

        telnowrong.setForeground(new java.awt.Color(204, 204, 204));
        telnowrong.setText("+16718768379");

        btnclearpdatapanel.setText("Clear");
        btnclearpdatapanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearpdatapanelActionPerformed(evt);
            }
        });

        faxnowrong.setForeground(new java.awt.Color(204, 204, 204));
        faxnowrong.setText("+18878987888");
        faxnowrong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                faxnowrongKeyReleased(evt);
            }
        });

        medrecnowrong.setForeground(new java.awt.Color(204, 204, 204));
        medrecnowrong.setText("eg : MR12345");

        banknowrong.setForeground(new java.awt.Color(204, 204, 204));
        banknowrong.setText("eg:9898767656");

        jLabel1.setText("Medical Beneficiary No(MBI):");

        bennotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bennotfKeyReleased(evt);
            }
        });

        bennowrong.setForeground(new java.awt.Color(204, 204, 204));

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("eg:1EG4-TE5-MK72");

        addemailchkbx.setText("Add Email");
        addemailchkbx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addemailchkbxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addemailchkbxMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addemailchkbxMousePressed(evt);
            }
        });
        addemailchkbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addemailchkbxActionPerformed(evt);
            }
        });
        addemailchkbx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addemailchkbxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addemailchkbxKeyTyped(evt);
            }
        });

        chkbxaddno.setText("Add no");
        chkbxaddno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkbxaddnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chkbxaddnoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chkbxaddnoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                chkbxaddnoMouseReleased(evt);
            }
        });
        chkbxaddno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkbxaddnoActionPerformed(evt);
            }
        });
        chkbxaddno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chkbxaddnoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chkbxaddnoKeyReleased(evt);
            }
        });

        addnotf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnotfActionPerformed(evt);
            }
        });
        addnotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addnotfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addnotfKeyTyped(evt);
            }
        });

        addemailtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addemailtfKeyReleased(evt);
            }
        });

        jLabel3.setText("Unique Identifier");

        uniquenotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uniquenotfKeyReleased(evt);
            }
        });

        uniquenowrong.setForeground(new java.awt.Color(204, 204, 204));
        uniquenowrong.setText("eg:3F2504E0-4F89-41D3-9A0C-0305E82C3301");

        javax.swing.GroupLayout personaldatapanelLayout = new javax.swing.GroupLayout(personaldatapanel);
        personaldatapanel.setLayout(personaldatapanelLayout);
        personaldatapanelLayout.setHorizontalGroup(
            personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaldatapanelLayout.createSequentialGroup()
                .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personaldatapanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uniquenowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personaldatapanelLayout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(banknowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(personaldatapanelLayout.createSequentialGroup()
                                        .addGap(164, 164, 164)
                                        .addComponent(bennowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(uniquenotf, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(personaldatapanelLayout.createSequentialGroup()
                                            .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(emailwrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ssnwrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(medrecnowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(53, 53, 53)
                                            .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(banknotf, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(medrecnotf, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ssntf, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(bennotf, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(emailtf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(personaldatapanelLayout.createSequentialGroup()
                                .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ssnlbl)
                                    .addComponent(faxnolbl)
                                    .addComponent(emaillbl)
                                    .addComponent(medrecnolbl)
                                    .addComponent(banknolbl)
                                    .addComponent(telnolbl))
                                .addGap(92, 92, 92)
                                .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telnowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(faxnowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(telnotf, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(faxnotf, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(personaldatapanelLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addemailchkbx)
                                            .addComponent(addnotf, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addemailtf, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(personaldatapanelLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(chkbxaddno, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(personaldatapanelLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(btnsavepd)
                        .addGap(67, 67, 67)
                        .addComponent(btnclearpdatapanel)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        personaldatapanelLayout.setVerticalGroup(
            personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaldatapanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personaldatapanelLayout.createSequentialGroup()
                        .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telnotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telnowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telnolbl)
                            .addComponent(chkbxaddno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(faxnowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(faxnotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addnotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(faxnolbl))
                .addGap(18, 18, 18)
                .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ssnlbl)
                    .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ssnwrong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ssntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailwrong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emaillbl)
                    .addComponent(addemailchkbx))
                .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personaldatapanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(medrecnolbl)
                                .addComponent(medrecnowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(medrecnotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(personaldatapanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(addemailtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personaldatapanelLayout.createSequentialGroup()
                        .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(banknowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(banknolbl))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personaldatapanelLayout.createSequentialGroup()
                        .addComponent(banknotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bennotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(bennowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(uniquenotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(uniquenowrong)
                .addGap(28, 28, 28)
                .addGroup(personaldatapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsavepd)
                    .addComponent(btnclearpdatapanel))
                .addGap(74, 74, 74))
        );

        nextchkbx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nextchkbx.setForeground(new java.awt.Color(255, 255, 255));
        nextchkbx.setText("NEXT-->");
        nextchkbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextchkbxActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        licensenolbl.setText("License No:");

        licensenotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                licensenotfKeyReleased(evt);
            }
        });

        vehiclenolbl.setText("Vehicle Identifier(VIN):");

        vehiclenotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vehiclenotfKeyReleased(evt);
            }
        });

        devicenolbl.setText("Device Identifier:");

        devicenotf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devicenotfActionPerformed(evt);
            }
        });
        devicenotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                devicenotfKeyReleased(evt);
            }
        });

        ipalbl.setText("IPA:");

        ipatf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ipatfKeyReleased(evt);
            }
        });

        linkedinlbl.setText("LinkedIn:");

        linkedintf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                linkedintfKeyReleased(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        licensenowrong.setForeground(new java.awt.Color(204, 204, 204));
        licensenowrong.setText("eg: SA89889899");

        linkedinwrong.setForeground(new java.awt.Color(204, 204, 204));
        linkedinwrong.setText("http://nl.linkedin.com/in/name");

        vehiclenowrong.setForeground(new java.awt.Color(204, 204, 204));
        vehiclenowrong.setText("eg:SALVA2AE4EH877322");

        btnclearprodatapanel.setText("Clear");
        btnclearprodatapanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearprodatapanelActionPerformed(evt);
            }
        });

        ipawrong.setForeground(new java.awt.Color(204, 204, 204));
        ipawrong.setText("eg:255.255.255.255");

        devicenowrong.setBackground(new java.awt.Color(204, 204, 204));
        devicenowrong.setForeground(new java.awt.Color(204, 204, 204));
        devicenowrong.setText("eg: 876-876-8789");

        serialnolbl.setText("Vehicle License No:");

        serialnotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serialnotfKeyReleased(evt);
            }
        });

        serialnowrong.setForeground(new java.awt.Color(204, 204, 204));
        serialnowrong.setText("eg: 215AB2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnclearprodatapanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(devicenolbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(licensenolbl)
                                .addGap(116, 116, 116)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehiclenowrong)
                                    .addComponent(licensenowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(vehiclenolbl))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vehiclenotf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(licensenotf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ipawrong, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(linkedinwrong)
                                    .addComponent(devicenowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(serialnowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ipalbl)
                            .addComponent(linkedinlbl)
                            .addComponent(serialnolbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ipatf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(linkedintf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(devicenotf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serialnotf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licensenolbl)
                    .addComponent(licensenotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licensenowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(vehiclenolbl)
                                    .addGap(74, 74, 74)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(devicenolbl)
                                        .addComponent(devicenowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(devicenotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(vehiclenowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vehiclenotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(serialnowrong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(serialnotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(121, 121, 121)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(serialnolbl)
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ipalbl)
                                    .addComponent(ipawrong, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ipatf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(linkedinlbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(linkedintf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(linkedinwrong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnclearprodatapanel))
                .addGap(22, 22, 22))
        );

        btnupload.setText("Upload Image");
        btnupload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnuploadMouseClicked(evt);
            }
        });
        btnupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Click to Enter Details");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jCheckBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckBox1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnupload, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nextchkbx)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(gdatapanel, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personaldatapanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(550, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gdatapanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(nextchkbx, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnupload, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(personaldatapanel, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(432, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBox1KeyPressed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jCheckBox1KeyPressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        nextchkbx.setVisible(false);
        if(jCheckBox1.isSelected()==true)
        {
            gdatapanel.setVisible(true);
            nextchkbx.setVisible(true);
        }else
        {
            gdatapanel.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void nextchkbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextchkbxActionPerformed
        // TODO add your handling code here:
        
        if(nextchkbx.isSelected()==true){
            personaldatapanel.setVisible(true);
        }else{
            personaldatapanel.setVisible(false);
        }
    }//GEN-LAST:event_nextchkbxActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this, "saved");
        
        
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnsavepdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavepdActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "saved");
        jPanel1.setVisible(true);
        
             
    }//GEN-LAST:event_btnsavepdActionPerformed

    private void emailtfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailtfKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_emailtfKeyTyped

    private void nametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nametfActionPerformed

    private void nametfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nametfKeyTyped
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_nametfKeyTyped

    private void nametfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nametfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametfKeyPressed

    private void nametfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nametfKeyReleased
        // TODO add your handling code here:
        String REGEXNAME = "^[a-zA-Z]{1,}(?: [a-zA-Z]+)?(?: [a-zA-Z]+)?$";
        Pattern p1 = Pattern.compile(REGEXNAME);
        Matcher match = p1.matcher(nametf.getText());
        
        if(match.matches()==true){
             p.setName(nametf.getText());
            namewrong.setText(null);
        }else{
            p.setName(null);
            namewrong.setText("INVALID");
        }
    }//GEN-LAST:event_nametfKeyReleased

    private void citytfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_citytfKeyReleased
        // TODO add your handling code here:
        String REGEXCITY = "^[a-zA-Z]{0,15}$";
        Pattern p2 = Pattern.compile(REGEXCITY);
        Matcher match2 = p2.matcher(citytf.getText());
        
        if(match2.matches()==true){
            p.setCity(citytf.getText());
            citywrong.setText(null);
        }else{
            citywrong.setText("INVALID");
        }
    }//GEN-LAST:event_citytfKeyReleased

    private void countrytfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countrytfKeyReleased
        // TODO add your handling code here:
        String REGEXCOUNTRY = "^[a-zA-Z]{0,15}$";
        Pattern p3 = Pattern.compile(REGEXCOUNTRY);
        Matcher match3 = p3.matcher(countrytf.getText());
        
        if(match3.matches()==true){
            p.setCountry(countrytf.getText());
            countrywrong.setText(null);
        }else{
            countrywrong.setText("INVALID");
        }
    }//GEN-LAST:event_countrytfKeyReleased

    private void ssntfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ssntfKeyReleased
        // TODO add your handling code here:
        String REGEXSSN = "^(?!000|666)[0-8][0-9]{2}-(?!00)[0-9]{2}-(?!0000)[0-9]{4}$";
        Pattern p4 = Pattern.compile(REGEXSSN);
        Matcher match4 = p4.matcher(ssntf.getText());
        
        if(match4.matches()==true){
            p.setSsn(ssntf.getText());
            ssnwrong.setText(null);
        }else{
            ssnwrong.setText("INVALID");
            ssnwrong.setForeground(Color.red);
            
        }
    }//GEN-LAST:event_ssntfKeyReleased

    private void emailtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailtfKeyReleased
        // TODO add your handling code here:
        String REGEXEMAIL = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern p5 = Pattern.compile(REGEXEMAIL);
        Matcher match5 = p5.matcher(emailtf.getText());
        
        if(match5.matches()){
             p.setEmail(emailtf.getText());
            emailwrong.setText(null);
        }else{
            emailwrong.setText("INVALID");
            emailwrong.setForeground(Color.red);
        }
        
    }//GEN-LAST:event_emailtfKeyReleased

    private void emailwrongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailwrongKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_emailwrongKeyReleased

    private void btnuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("png","jpg","jpeg");
        filechooser.setFileFilter(filter);
        int fileselect = filechooser.showOpenDialog(null);
        
        if(fileselect == JFileChooser.APPROVE_OPTION)
        {
            File file = filechooser.getSelectedFile();
            p.setImage_upload(file.getAbsolutePath());
            JOptionPane.showMessageDialog(null, "Image Uploaded."); 
            
        }
    }//GEN-LAST:event_btnuploadActionPerformed

    private void telnotfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telnotfActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_telnotfActionPerformed

    private void telnotfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telnotfKeyTyped
        // TODO add your handling code here:
    
       
    }//GEN-LAST:event_telnotfKeyTyped

    private void telnotfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telnotfKeyReleased
        // TODO add your handling code here:
       String mobno = telnotf.getText();
       if(mobno.matches("^\\+1[2-9][0-9]{9}"))
       {
           p.setTelno(telnotf.getText());
           telnowrong.setText(null);
       }
       else
       {telnowrong.setText("INVALID");
       telnowrong.setForeground(Color.red);
       }     
    }//GEN-LAST:event_telnotfKeyReleased

    private void emailtfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailtfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtfKeyPressed

    private void btncleargdatapanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncleargdatapanelActionPerformed
        // TODO add your handling code here:
        nametf.setText("");
        
        citytf.setText("");
        countrytf.setText("");
    }//GEN-LAST:event_btncleargdatapanelActionPerformed

    private void btnclearpdatapanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearpdatapanelActionPerformed
        // TODO add your handling code here:
        telnotf.setText("");
        faxnotf.setText("");
        ssntf.setText("");
        emailtf.setText("");
        medrecnotf.setText("");
        banknotf.setText("");
    }//GEN-LAST:event_btnclearpdatapanelActionPerformed

    private void datechsrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datechsrMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_datechsrMouseClicked

    private void faxnotfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_faxnotfKeyReleased
        // TODO add your handling code here:
        
        String REGEXFAX = "\\+1[2-9][0-9]{9}";
        Pattern p3 = Pattern.compile(REGEXFAX);
        Matcher match3 = p3.matcher(faxnotf.getText());
       if(match3.matches())
       {
           p.setFaxno(faxnotf.getText());
           faxnowrong.setText(null);
       }
       else
       {faxnowrong.setText("INVALID");
        faxnowrong.setForeground(Color.red);
       }   
    }//GEN-LAST:event_faxnotfKeyReleased

    private void faxnowrongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_faxnowrongKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_faxnowrongKeyReleased

    private void medrecnotfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_medrecnotfKeyReleased
        // TODO add your handling code here:
      
        String REGEXMED = "[a-zA-Z][a-zA-Z]\\d{5,6}";
        Pattern p8 = Pattern.compile(REGEXMED);
        Matcher match8 = p8.matcher(medrecnotf.getText());
       if(match8.matches())
       {
           p.setMed_rec_no(medrecnotf.getText());
           medrecnowrong.setText(null);
       }
       else
       {   medrecnowrong.setText("INVALID");
           medrecnowrong.setForeground(Color.red);
       }   
        
    }//GEN-LAST:event_medrecnotfKeyReleased

    private void banknotfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_banknotfKeyReleased
        // TODO add your handling code here:\W*\d{8,17}\b
        
        String REGEXBANK = "^[0-9]{7,14}$";
        Pattern p12 = Pattern.compile(REGEXBANK);
        Matcher match12 = p12.matcher(banknotf.getText());
       if(match12.matches())
       {
           p.setBank_acc_no(banknotf.getText());
           banknowrong.setText(null);
       }
       else
       {banknowrong.setText("INVALID");
       banknowrong.setForeground(Color.red);
       }   
    }//GEN-LAST:event_banknotfKeyReleased

    private void btnuploadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnuploadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnuploadMouseClicked

    private void chkbxaddnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkbxaddnoActionPerformed
        // TODO add your handling code here:
        if(chkbxaddno.isSelected()==true)
        {
            addnotf.setBackground(Color.WHITE);
            addnotf.setVisible(true);
            
        }
        
    }//GEN-LAST:event_chkbxaddnoActionPerformed

    private void addnotfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addnotfKeyReleased
        // TODO add your handling code here:
        
        String mobno = addnotf.getText();
       if(mobno.matches("^\\+1[2-9][0-9]{9}"))
       {
           p.setExtrano(addnotf.getText());
           telnowrong.setText(null);
       }
       else
       {telnowrong.setText("INVALID");
       telnowrong.setForeground(Color.red);
       }
        
    }//GEN-LAST:event_addnotfKeyReleased

    private void addnotfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addnotfKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_addnotfKeyTyped

    private void addnotfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnotfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addnotfActionPerformed

    private void chkbxaddnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkbxaddnoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chkbxaddnoMouseClicked

    private void chkbxaddnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chkbxaddnoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chkbxaddnoKeyPressed

    private void chkbxaddnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkbxaddnoMousePressed
        // TODO add your handling code here:
        if(chkbxaddno.isSelected()==true)
        {
            addnotf.setVisible(true);
            
        }
        
    }//GEN-LAST:event_chkbxaddnoMousePressed

    private void chkbxaddnoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkbxaddnoMouseReleased
        // TODO add your handling code here:
        if(chkbxaddno.isSelected()==true)
        {
            addnotf.setVisible(true);
            
        }
        
    }//GEN-LAST:event_chkbxaddnoMouseReleased

    private void chkbxaddnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkbxaddnoMouseEntered
        // TODO add your handling code here:
        if(chkbxaddno.isSelected()==true)
        {
            addnotf.setVisible(true);
            
        }
        
    }//GEN-LAST:event_chkbxaddnoMouseEntered

    private void datechsrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datechsrKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_datechsrKeyReleased

    private void medrecnotfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medrecnotfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medrecnotfActionPerformed

    private void serialnotfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serialnotfKeyReleased
        // TODO add your handling code here:
        String REGEXSERIALNO = "^[A-Z0-9]{6}";
        Pattern p13 = Pattern.compile(REGEXSERIALNO);
        Matcher match13 = p13.matcher(serialnotf.getText());
        if(match13.matches()){
            p.setDeviceno(serialnotf.getText());
            serialnowrong.setText(null);
        }else
        {
            serialnowrong.setText("INVALID");
            serialnowrong.setForeground(Color.red);
        }
    }//GEN-LAST:event_serialnotfKeyReleased

    private void btnclearprodatapanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearprodatapanelActionPerformed
        // TODO add your handling code here:
        licensenotf.setText("");
        vehiclenotf.setText("");
        devicenotf.setText("");
        ipatf.setText("");
        linkedintf.setText("");

    }//GEN-LAST:event_btnclearprodatapanelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        btnupload.setVisible(true);
        JOptionPane.showMessageDialog(this, "saved");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void linkedintfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linkedintfKeyReleased
        // TODO add your handling code here:
        String REGEXLINKEDIN = "^https?://((www|\\w\\w)\\.)?linkedin.com/((in/[^/]+/?)|(pub/[^/]+/((\\w|\\d)+/?){3}))$";
        Pattern p11 = Pattern.compile(REGEXLINKEDIN);
        Matcher match11 = p11.matcher(linkedintf.getText());
        if(match11.matches())
        {
            p.setLinkedin(linkedintf.getText());
            linkedinwrong.setText(null);
        }
        else
        {linkedinwrong.setText("INVALID");
            linkedinwrong.setForeground(Color.red);
        }
    }//GEN-LAST:event_linkedintfKeyReleased

    private void ipatfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ipatfKeyReleased
        // TODO add your handling code here:

        String REGEXIPA = "^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$";
        Pattern p9 = Pattern.compile(REGEXIPA);
        Matcher match9 = p9.matcher(ipatf.getText());
        if(match9.matches())
        {
            p.setIPA(ipatf.getText());
            ipawrong.setText(null);
        }
        else
        {ipawrong.setText("INVALID");
            ipawrong.setForeground(Color.red);
        }
    }//GEN-LAST:event_ipatfKeyReleased

    private void devicenotfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_devicenotfKeyReleased
        // TODO add your handling code here:
        String REGEXDEVNO = "^[1-9]\\d{2}-\\d{3}-\\d{4}$";
        Pattern p12 = Pattern.compile(REGEXDEVNO);
        Matcher match12 = p12.matcher(devicenotf.getText());
        if(match12.matches()){
            p.setDeviceno(devicenotf.getText());
            devicenowrong.setText(null);
        }else
        {
            devicenowrong.setText("INVALID");
            devicenowrong.setForeground(Color.red);
        }

    }//GEN-LAST:event_devicenotfKeyReleased

    private void devicenotfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devicenotfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_devicenotfActionPerformed

    private void vehiclenotfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vehiclenotfKeyReleased
        // TODO add your handling code here:
        String REGEXVEHNO = "^\\b[(A-H|J-N|P|R-Z|0-9)]{17}\\b";
        Pattern p10 = Pattern.compile(REGEXVEHNO);
        Matcher match10 = p10.matcher(vehiclenotf.getText());
        if(match10.matches())
        {
            p.setVehicleno(vehiclenotf.getText());
            vehiclenowrong.setText(null);
        }
        else
        {vehiclenowrong.setText("INVALID");
            vehiclenowrong.setForeground(Color.red);
        }
    }//GEN-LAST:event_vehiclenotfKeyReleased

    private void licensenotfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_licensenotfKeyReleased
        // TODO add your handling code here:

        String REGEXLICENSENO = "^[A-Z]{2}[0-9]{7}";
        Pattern p7 = Pattern.compile(REGEXLICENSENO);
        Matcher match7 = p7.matcher(licensenotf.getText());

        if(match7.matches()){
            p.setLicenseno(licensenotf.getText());
            licensenowrong.setText(null);
        }else{
            licensenowrong.setText("INVALID");
            licensenowrong.setForeground(Color.red);
        }

    }//GEN-LAST:event_licensenotfKeyReleased

    private void bennotfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bennotfKeyReleased
        // TODO add your handling code here:
        String REGEXBENNO = "^[1-9][^SLOIBZsloibz0-9][^SLOIBZsloibz][0-9]-?[^SLOIBZsloibz0-9][^SLOIBZsloibz][0-9]-?[^SLOIBZsloibz0-9][^SLOIBZsloibz0-9][0-9][0-9]$";
        Pattern p14 = Pattern.compile(REGEXBENNO);
        Matcher match14 = p14.matcher(bennotf.getText());

        if(match14.matches()){
            p.setBeneficiary_num(bennotf.getText());
            bennowrong.setText(null);
        }else{
            bennowrong.setText("INVALID");
            bennowrong.setForeground(Color.red);
        }
    }//GEN-LAST:event_bennotfKeyReleased

    private void ssntfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssntfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssntfActionPerformed

    private void addemailchkbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addemailchkbxActionPerformed
        // TODO add your handling code here:
        if(addemailchkbx.isSelected()==true)
        {
            addemailtf.setBackground(Color.WHITE);
            addemailtf.setVisible(true);
        }
            
        
    }//GEN-LAST:event_addemailchkbxActionPerformed

    private void addemailtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemailtfKeyReleased
        // TODO add your handling code here:
        String REGEXEMAIL2 = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern p15 = Pattern.compile(REGEXEMAIL2);
        Matcher match15 = p15.matcher(addemailtf.getText());
        
        if(match15.matches()){
             p.setExtraemail(addemailtf.getText());
            emailwrong.setText(null);
        }else{
            emailwrong.setText("INVALID");
            emailwrong.setForeground(Color.red);
        }
    }//GEN-LAST:event_addemailtfKeyReleased

    private void addemailchkbxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addemailchkbxMouseClicked
        // TODO add your handling code here:
        if(addemailchkbx.isSelected()==true)
        {
            addemailtf.setVisible(true);
        }
    }//GEN-LAST:event_addemailchkbxMouseClicked

    private void addemailchkbxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addemailchkbxMousePressed
        // TODO add your handling code here:
         if(addemailchkbx.isSelected()==true)
        {
            addemailtf.setVisible(true);
        }else{
            addemailtf.setVisible(false);
         }
    }//GEN-LAST:event_addemailchkbxMousePressed

    private void addemailchkbxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addemailchkbxMouseEntered
        // TODO add your handling code here:
         if(addemailchkbx.isSelected()==true)
        {
            addemailtf.setVisible(true);
        }
    }//GEN-LAST:event_addemailchkbxMouseEntered

    private void addemailchkbxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemailchkbxKeyTyped
        // TODO add your handling code here:
         if(addemailchkbx.isSelected()==true)
        {
            addemailtf.setVisible(true);
        }else{
            addemailtf.setVisible(false);
        }
    }//GEN-LAST:event_addemailchkbxKeyTyped

    private void addemailchkbxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addemailchkbxKeyPressed
        // TODO add your handling code here:
         if(addemailchkbx.isSelected()==true)
        {
            addemailtf.setVisible(true);
        }
    }//GEN-LAST:event_addemailchkbxKeyPressed

    private void chkbxaddnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chkbxaddnoKeyReleased
        // TODO add your handling code here:
         if(addemailchkbx.isSelected()==true)
        {
            addemailtf.setVisible(true);
        }else{
            addemailtf.setVisible(false);
        }
    }//GEN-LAST:event_chkbxaddnoKeyReleased

    private void uniquenotfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uniquenotfKeyReleased
        // TODO add your handling code here:
         String REGEXUNIQUENO = "/^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$/";
        Pattern p16 = Pattern.compile(REGEXUNIQUENO);
        Matcher match16 = p16.matcher(uniquenotf.getText());
        
        if(match16.matches()){
             p.setUniqueno(uniquenotf.getText());
             uniquenowrong.setText(null);
        }else{
            uniquenowrong.setText("INVALID");
            uniquenowrong.setForeground(Color.red);
        }
    }//GEN-LAST:event_uniquenotfKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox addemailchkbx;
    private javax.swing.JTextField addemailtf;
    private javax.swing.JTextField addnotf;
    private javax.swing.JLabel banknolbl;
    private javax.swing.JTextField banknotf;
    private javax.swing.JLabel banknowrong;
    private javax.swing.JTextField bennotf;
    private javax.swing.JLabel bennowrong;
    private javax.swing.JButton btncleargdatapanel;
    private javax.swing.JButton btnclearpdatapanel;
    private javax.swing.JButton btnclearprodatapanel;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsavepd;
    private javax.swing.JButton btnupload;
    private javax.swing.JCheckBox chkbxaddno;
    private javax.swing.JLabel citylbl;
    private javax.swing.JTextField citytf;
    private javax.swing.JLabel citywrong;
    private javax.swing.JLabel countrylbl;
    private javax.swing.JTextField countrytf;
    private javax.swing.JLabel countrywrong;
    private com.toedter.calendar.JDateChooser datechsr;
    private javax.swing.JLabel devicenolbl;
    private javax.swing.JTextField devicenotf;
    private javax.swing.JLabel devicenowrong;
    private javax.swing.JLabel doblbl;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JTextField emailtf;
    private javax.swing.JLabel emailwrong;
    private javax.swing.JLabel faxnolbl;
    private javax.swing.JTextField faxnotf;
    private javax.swing.JLabel faxnowrong;
    private javax.swing.JPanel gdatapanel;
    private javax.swing.JLabel ipalbl;
    private javax.swing.JTextField ipatf;
    private javax.swing.JLabel ipawrong;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel licensenolbl;
    private javax.swing.JTextField licensenotf;
    private javax.swing.JLabel licensenowrong;
    private javax.swing.JLabel linkedinlbl;
    private javax.swing.JTextField linkedintf;
    private javax.swing.JLabel linkedinwrong;
    private javax.swing.JLabel medrecnolbl;
    private javax.swing.JTextField medrecnotf;
    private javax.swing.JLabel medrecnowrong;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametf;
    private javax.swing.JLabel namewrong;
    private javax.swing.JCheckBox nextchkbx;
    private javax.swing.JPanel personaldatapanel;
    private javax.swing.JLabel serialnolbl;
    private javax.swing.JTextField serialnotf;
    private javax.swing.JLabel serialnowrong;
    private javax.swing.JLabel ssnlbl;
    private javax.swing.JTextField ssntf;
    private javax.swing.JLabel ssnwrong;
    private javax.swing.JLabel telnolbl;
    private javax.swing.JTextField telnotf;
    private javax.swing.JLabel telnowrong;
    private javax.swing.JTextField uniquenotf;
    private javax.swing.JLabel uniquenowrong;
    private javax.swing.JLabel vehiclenolbl;
    private javax.swing.JTextField vehiclenotf;
    private javax.swing.JLabel vehiclenowrong;
    // End of variables declaration//GEN-END:variables
}
